// AUTO-GENERATED by scripts/gen_g300_int8_assets.py -- do not edit by hand.
// int8 requantization constants for the DLA-backed G300 pipeline.
localparam integer G300_REQ_SHIFT    = 16;
localparam integer G300_REQ_SHIFT_L4 = 16;
localparam signed [63:0] G300_MA0 = 64'sd755;
localparam signed [63:0] G300_MB0 = 64'sd52419;
localparam signed [63:0] G300_MA2 = 64'sd1435;
localparam signed [63:0] G300_MB2 = 64'sd25896;
localparam signed [63:0] G300_MW4 = 64'sd44971316;
localparam signed [63:0] G300_MB4 = 64'sd437099189;
