// AUTO-GENERATED by scripts/gan_golden.py -- do not edit by hand.
// 9-segment piecewise-linear activation tables, Q4.12.
// TANH/SIGMOID coefficients are taken verbatim from
//   UAS_VLSI_Kelompok05_modified/UAS_VLSI/pla_activations.v
// RELU/LRELU/IDENT reuse the same datapath with a single split at zero.
// LOG2M is a minimax fit of 4096*log2(x/4096) on x in [4096, 8192),
// used by gan_nlog.v to turn a sigmoid score into a BCE loss term.

localparam signed [15:0] PWL_THR_TANH_0 = -16'sd20480;
localparam signed [15:0] PWL_THR_TANH_1 = -16'sd12288;
localparam signed [15:0] PWL_THR_TANH_2 = -16'sd6144;
localparam signed [15:0] PWL_THR_TANH_3 = -16'sd3072;
localparam signed [15:0] PWL_THR_TANH_4 =  16'sd3072;
localparam signed [15:0] PWL_THR_TANH_5 =  16'sd6144;
localparam signed [15:0] PWL_THR_TANH_6 =  16'sd12288;
localparam signed [15:0] PWL_THR_TANH_7 =  16'sd20480;

localparam signed [15:0] PWL_THR_LOG2M_0 =  16'sd4551;
localparam signed [15:0] PWL_THR_LOG2M_1 =  16'sd5006;
localparam signed [15:0] PWL_THR_LOG2M_2 =  16'sd5461;
localparam signed [15:0] PWL_THR_LOG2M_3 =  16'sd5916;
localparam signed [15:0] PWL_THR_LOG2M_4 =  16'sd6372;
localparam signed [15:0] PWL_THR_LOG2M_5 =  16'sd6827;
localparam signed [15:0] PWL_THR_LOG2M_6 =  16'sd7282;
localparam signed [15:0] PWL_THR_LOG2M_7 =  16'sd7737;

localparam signed [15:0] PWL_M_TANH_0 =  16'sd0;  localparam signed [15:0] PWL_C_TANH_0 = -16'sd4093;
localparam signed [15:0] PWL_M_TANH_1 =  16'sd10;  localparam signed [15:0] PWL_C_TANH_1 = -16'sd4046;
localparam signed [15:0] PWL_M_TANH_2 =  16'sd246;  localparam signed [15:0] PWL_C_TANH_2 = -16'sd3339;
localparam signed [15:0] PWL_M_TANH_3 =  16'sd1475;  localparam signed [15:0] PWL_C_TANH_3 = -16'sd1496;
localparam signed [15:0] PWL_M_TANH_4 =  16'sd3469;  localparam signed [15:0] PWL_C_TANH_4 =  16'sd0;
localparam signed [15:0] PWL_M_TANH_5 =  16'sd1475;  localparam signed [15:0] PWL_C_TANH_5 =  16'sd1496;
localparam signed [15:0] PWL_M_TANH_6 =  16'sd246;  localparam signed [15:0] PWL_C_TANH_6 =  16'sd3339;
localparam signed [15:0] PWL_M_TANH_7 =  16'sd10;  localparam signed [15:0] PWL_C_TANH_7 =  16'sd4046;
localparam signed [15:0] PWL_M_TANH_8 =  16'sd0;  localparam signed [15:0] PWL_C_TANH_8 =  16'sd4093;

localparam signed [15:0] PWL_M_SIGMOID_0 =  16'sd21;  localparam signed [15:0] PWL_C_SIGMOID_0 =  16'sd130;
localparam signed [15:0] PWL_M_SIGMOID_1 =  16'sd83;  localparam signed [15:0] PWL_C_SIGMOID_1 =  16'sd445;
localparam signed [15:0] PWL_M_SIGMOID_2 =  16'sd369;  localparam signed [15:0] PWL_C_SIGMOID_2 =  16'sd1300;
localparam signed [15:0] PWL_M_SIGMOID_3 =  16'sd756;  localparam signed [15:0] PWL_C_SIGMOID_3 =  16'sd1881;
localparam signed [15:0] PWL_M_SIGMOID_4 =  16'sd979;  localparam signed [15:0] PWL_C_SIGMOID_4 =  16'sd2048;
localparam signed [15:0] PWL_M_SIGMOID_5 =  16'sd756;  localparam signed [15:0] PWL_C_SIGMOID_5 =  16'sd2215;
localparam signed [15:0] PWL_M_SIGMOID_6 =  16'sd369;  localparam signed [15:0] PWL_C_SIGMOID_6 =  16'sd2796;
localparam signed [15:0] PWL_M_SIGMOID_7 =  16'sd83;  localparam signed [15:0] PWL_C_SIGMOID_7 =  16'sd3651;
localparam signed [15:0] PWL_M_SIGMOID_8 =  16'sd21;  localparam signed [15:0] PWL_C_SIGMOID_8 =  16'sd3966;

localparam signed [15:0] PWL_M_RELU_0 =  16'sd0;  localparam signed [15:0] PWL_C_RELU_0 =  16'sd0;
localparam signed [15:0] PWL_M_RELU_1 =  16'sd4096;  localparam signed [15:0] PWL_C_RELU_1 =  16'sd0;
localparam signed [15:0] PWL_M_RELU_2 =  16'sd4096;  localparam signed [15:0] PWL_C_RELU_2 =  16'sd0;
localparam signed [15:0] PWL_M_RELU_3 =  16'sd4096;  localparam signed [15:0] PWL_C_RELU_3 =  16'sd0;
localparam signed [15:0] PWL_M_RELU_4 =  16'sd4096;  localparam signed [15:0] PWL_C_RELU_4 =  16'sd0;
localparam signed [15:0] PWL_M_RELU_5 =  16'sd4096;  localparam signed [15:0] PWL_C_RELU_5 =  16'sd0;
localparam signed [15:0] PWL_M_RELU_6 =  16'sd4096;  localparam signed [15:0] PWL_C_RELU_6 =  16'sd0;
localparam signed [15:0] PWL_M_RELU_7 =  16'sd4096;  localparam signed [15:0] PWL_C_RELU_7 =  16'sd0;
localparam signed [15:0] PWL_M_RELU_8 =  16'sd4096;  localparam signed [15:0] PWL_C_RELU_8 =  16'sd0;

localparam signed [15:0] PWL_M_LRELU_0 =  16'sd819;  localparam signed [15:0] PWL_C_LRELU_0 =  16'sd0;
localparam signed [15:0] PWL_M_LRELU_1 =  16'sd4096;  localparam signed [15:0] PWL_C_LRELU_1 =  16'sd0;
localparam signed [15:0] PWL_M_LRELU_2 =  16'sd4096;  localparam signed [15:0] PWL_C_LRELU_2 =  16'sd0;
localparam signed [15:0] PWL_M_LRELU_3 =  16'sd4096;  localparam signed [15:0] PWL_C_LRELU_3 =  16'sd0;
localparam signed [15:0] PWL_M_LRELU_4 =  16'sd4096;  localparam signed [15:0] PWL_C_LRELU_4 =  16'sd0;
localparam signed [15:0] PWL_M_LRELU_5 =  16'sd4096;  localparam signed [15:0] PWL_C_LRELU_5 =  16'sd0;
localparam signed [15:0] PWL_M_LRELU_6 =  16'sd4096;  localparam signed [15:0] PWL_C_LRELU_6 =  16'sd0;
localparam signed [15:0] PWL_M_LRELU_7 =  16'sd4096;  localparam signed [15:0] PWL_C_LRELU_7 =  16'sd0;
localparam signed [15:0] PWL_M_LRELU_8 =  16'sd4096;  localparam signed [15:0] PWL_C_LRELU_8 =  16'sd0;

localparam signed [15:0] PWL_M_IDENT_0 =  16'sd4096;  localparam signed [15:0] PWL_C_IDENT_0 =  16'sd0;
localparam signed [15:0] PWL_M_IDENT_1 =  16'sd4096;  localparam signed [15:0] PWL_C_IDENT_1 =  16'sd0;
localparam signed [15:0] PWL_M_IDENT_2 =  16'sd4096;  localparam signed [15:0] PWL_C_IDENT_2 =  16'sd0;
localparam signed [15:0] PWL_M_IDENT_3 =  16'sd4096;  localparam signed [15:0] PWL_C_IDENT_3 =  16'sd0;
localparam signed [15:0] PWL_M_IDENT_4 =  16'sd4096;  localparam signed [15:0] PWL_C_IDENT_4 =  16'sd0;
localparam signed [15:0] PWL_M_IDENT_5 =  16'sd4096;  localparam signed [15:0] PWL_C_IDENT_5 =  16'sd0;
localparam signed [15:0] PWL_M_IDENT_6 =  16'sd4096;  localparam signed [15:0] PWL_C_IDENT_6 =  16'sd0;
localparam signed [15:0] PWL_M_IDENT_7 =  16'sd4096;  localparam signed [15:0] PWL_C_IDENT_7 =  16'sd0;
localparam signed [15:0] PWL_M_IDENT_8 =  16'sd4096;  localparam signed [15:0] PWL_C_IDENT_8 =  16'sd0;

localparam signed [15:0] PWL_M_LOG2M_0 =  16'sd5604;  localparam signed [15:0] PWL_C_LOG2M_0 = -16'sd5600;
localparam signed [15:0] PWL_M_LOG2M_1 =  16'sd5069;  localparam signed [15:0] PWL_C_LOG2M_1 = -16'sd5006;
localparam signed [15:0] PWL_M_LOG2M_2 =  16'sd4628;  localparam signed [15:0] PWL_C_LOG2M_2 = -16'sd4468;
localparam signed [15:0] PWL_M_LOG2M_3 =  16'sd4257;  localparam signed [15:0] PWL_C_LOG2M_3 = -16'sd3974;
localparam signed [15:0] PWL_M_LOG2M_4 =  16'sd3941;  localparam signed [15:0] PWL_C_LOG2M_4 = -16'sd3518;
localparam signed [15:0] PWL_M_LOG2M_5 =  16'sd3669;  localparam signed [15:0] PWL_C_LOG2M_5 = -16'sd3095;
localparam signed [15:0] PWL_M_LOG2M_6 =  16'sd3432;  localparam signed [15:0] PWL_C_LOG2M_6 = -16'sd2700;
localparam signed [15:0] PWL_M_LOG2M_7 =  16'sd3224;  localparam signed [15:0] PWL_C_LOG2M_7 = -16'sd2330;
localparam signed [15:0] PWL_M_LOG2M_8 =  16'sd3040;  localparam signed [15:0] PWL_C_LOG2M_8 = -16'sd1983;

